package com.example.pristine_approval_portal.ui.allModel.purchaseOrderModel;

public class ApprovalModel {
    public boolean condition;
    public String message;
    public String id;
    public String table_id;
    public String documnet_type;
    public String document_no;
    public String sequence_no;
    public String approval_code;
    public String sender_id;
    public String salesperson_purchase_code;
    public String approver_id;
    public String status;
    public String date_time_sent_for_approval;
    public String last_datetime_modified;
    public String last_modified_by_user_id;
    public String comment;
    public String due_date;
    public String amount;
//    public String amount(LCY);
    public String currency_code;
    public String approval_type;
    public String limit_type;
//    public String avialble_credit_limit(LCY);
    public String pending_approvals;
    public String record_id_to_approve;
    public String delegationdateformula;
    public String number_of_approved_request;
    public String number_of_rejected_request;
    public String entry_no;
    public String workflowstepinstanceid;
    public String related_to_change;
    public String journal_template_name;
    public String journal_batch_name;
    public String grn_approval_request;
    public String account_no;
    public String account_name;
    public String narration;
    public String beneficiary_name;
    public String ifsc_code;
    public String bank_name;
    public String account_type;
    public String bank_account_no;
    public String account_type_code;
}
